insert into scrip_mapping (original_name, mapped_name)
values
('ACC LIMITED', 'ACC Ltd.'),
('ADANI PORTS AND SPEC', 'Adani Ports & Special Economic Zone Ltd.'),
('AMAR RAJA BATT FV1', 'Amara Raja Batteries Ltd.'),
('AMARARAJA BATTERIES', 'Amara Raja Batteries Ltd.'),
('APOLLO TYRES FV1', 'Apollo Tyres Ltd.'),
('ARVIND LIMITED', 'Arvind Ltd.'),
('ASAHI SONGWON COLORS', 'Asahi Songwon Colors Ltd.'),
('ASHOK LEYLAND', 'Ashok Leyland Ltd.'),
('BHARAT FORGE FV RS 2', 'Bharat Forge Ltd.'),
('BHARTI AIRTEL FV5', 'Bharti Airtel Ltd.'),
('BIOCON LTD', 'Biocon Ltd.'),
('CAIRN INDIA LTD', 'Cairn India Ltd.'),
('CASTROL INDIA FV5', 'Castrol India Ltd.'),
('CENTURY PLYBOARD FV1', 'Century Plyboards (India) Ltd.'),
('CG POWER AND IND LTD', 'CG Power and Industrial Solutions Ltd.'),
('CIPLA', 'Cipla Ltd.'),
('COAL INDIA LIMITED', 'Coal India Ltd.'),
('COLGATE EQ NEW', 'Colgate-Palmolive (India) Ltd.'),
('CROMPTON COMSUMER', 'Crompton Greaves Consumer Electricals Ltd.'),
('CROMPTON GREAVE FV2', 'Crompton Greaves Ltd.'),
('DABUR INDIA', 'Dabur India Ltd.'),
('DEEPAK FERTILIZERS', 'Deepak Fertilisers & Petrochemicals Corporation Ltd.'),
('DR REDDY''S LABS', 'Dr. Reddy''s Laboratories Ltd.'),
('E.I.D. PARRY FV1', 'EID Parry (India) Ltd.'),
('EVERADY NEW FV 5', 'Eveready Industries India Ltd.'),
('EXIDE INDUSTRIES FV1', 'Exide Industries Ltd.'),
('HCL TECHNOLOGIES', 'HCL Technologies Ltd.'),
('HINDUSTAN UNILEVER', 'Hindustan Unilever Ltd.'),
('I T C FV RE. 1', 'ITC Ltd.'),
('ICICI BANK LT FV2', 'ICICI Bank Ltd.'),
('INDIA CEMENTS', 'India Cements Ltd.'),
('INDIAN OIL CORPORA', 'Indian Oil Corporation Ltd.'),
('INFOSYS LIMITED', 'Infosys Ltd.'),
('JET AIRWAYS LTD.', 'Jet Airways (India) Ltd.'),
('JUBILANT FOODWORKS L', 'Jubilant Foodworks Ltd.'),
('L I C HOUSING FI FV2', 'LIC Housing Finance Ltd.'),
('LARSEN AND TOUBRO', 'Larsen & Toubro Ltd.'),
('MCLEOD RUSSEL INDIA', 'McLeod Russel (India) Ltd.'),
('NAVNEET EDU LTD', 'Navneet Education Ltd.'),
('NMDC LIMITED FV1', 'NMDC Ltd.'),
('NTPC LIMITED', 'NTPC Ltd.'),
('ONGC FV 5', 'Oil And Natural Gas Corporation Ltd.'),
('PUNJAB NATIONAL BK', 'Punjab National Bank'),
('RELIANCE POWER LTD', 'Reliance Power Ltd.'),
('S A I L', 'Steel Authority of India (SAIL) Ltd.'),
('SHREE RENUKA FV1', 'Shree Renuka Sugars Ltd.'),
('TATA CHEMICALS', 'Tata Chemicals Ltd.'),
('TATA COFFEE LTD FV1', 'Tata Coffee Ltd.'),
('TATA CONSULTANCY SER', 'Tata Consultancy Services Ltd.'),
('TATA GLOBAL BEVE.FV1', 'Tata Global Beverages Ltd.'),
('TATA POWER COMP FV1', 'Tata Power Company Ltd'),
('TATA STEEL LIMITED', 'Tata Steel Ltd.'),
('TN NEWSPRINT EQ', 'Tamil Nadu Newsprint And Papers Ltd.'),
('VEDANTA LIMITED', 'Vedanta Ltd.'),
('VRL LOGISTICS LIMITE', 'VRL Logistics Ltd.'),
('WELSPUN INDIA LD FV1', 'Welspun India Ltd.'),
('WIPRO', 'Wipro Ltd.'),
('YES BANK LTD FV2', 'YES Bank Ltd.');

insert into scrip_mapping (original_name, mapped_name)
values('SBI-ETF NIFTY', 'SBI ETF Nifty 50'),
('AXIS BANK LTD FV2', 'Axis Bank Ltd.'),
('YES BANK LTD LOCKING', 'YES Bank Ltd. - Locked'),
('STATE BANK OF IN FV1', 'State Bank of India'),
('VOLTAS LTD. FV1', 'Voltas Ltd.'),
('HDFC BANK LTD FV1', 'HDFC Bank Ltd.');

insert into scrip_mapping (original_name, mapped_name)
values('YES BANK LTD FV2 NEW', 'YES Bank Ltd.');




